# Generated by Django 6.0 on 2026-01-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='chapter_num',
            field=models.CharField(default=0, verbose_name=int),
        ),
    ]
