# Generated by Django 6.0 on 2026-01-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercices', '0002_category_chapter_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='chapter_num',
            field=models.IntegerField(default=0),
        ),
    ]
