# Generated by Django 6.0 on 2026-01-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercices', '0003_alter_category_chapter_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
    ]
