# Generated by Django 6.0 on 2026-01-03 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercices', '0004_remove_category_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='order',
            new_name='section_num',
        ),
    ]
