# Generated by Django 6.0 on 2026-01-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercices', '0005_rename_order_section_section_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
