# Generated by Django 6.0 on 2026-01-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercices', '0007_alter_section_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='icon',
            field=models.CharField(default='📄', max_length=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
