# Generated by Django 6.0 on 2026-01-03 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercices', '0008_section_icon_alter_section_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercices.category'),
        ),
    ]
