# Generated by Django 6.0 on 2026-01-03 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercices', '0009_alter_section_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='exercices.category'),
        ),
    ]
